---
apiVersion: v1
kind: Secret
metadata:
  name: vandal-vandal-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/vandal-gateway-gitops
